# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cloud_kicker}
  s.version = "0.0.0.pre1"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bob Burbach"]
  s.date = %q{2010-03-28}
  s.description = %q{      Rails abstraction layer for creating maps using the Cloudmade web framework. Makes creating maps with custom 
      color schemes, ajax markers and customizable marker info windows quick and easy.
}
  s.email = %q{govpulse@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "cloud_kicker.gemspec",
     "example/cloud_kicker.yml",
     "lib/critical_juncture/cloud_kicker.rb",
     "lib/critical_juncture/control_elements.rb",
     "lib/critical_juncture/map.rb",
     "lib/critical_juncture/map/map_bookmarking.rb",
     "lib/critical_juncture/map/map_events.rb",
     "lib/critical_juncture/map/map_location.rb",
     "lib/critical_juncture/markers/ajax_markers.rb",
     "lib/critical_juncture/markers/marker.rb",
     "test/helper.rb",
     "test/test_cloud_kicker.rb"
  ]
  s.homepage = %q{http://github.com/trifecta/cloud_kicker}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Rails abstraction layer for creating maps using the Cloudmade web framework.}
  s.test_files = [
    "test/helper.rb",
     "test/test_cloud_kicker.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

